<a href="https://colab.research.google.com/github/sutejym122/Data-Science-and-Machine-Learning-/blob/main/Task4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 4

Name - SUTEJ Y M

Reg no. - 10487

Import the numpy package under the name np and Print the numpy version and the configuration 

In [3]:
import numpy as np 
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


Create a null vector of size 10

In [5]:
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create Simple 1-D array and check type and check data types in array

In [9]:
x=np.array([1,2,3])
print(x)
print(type(x))
print(x.dtype)

[1 2 3]
<class 'numpy.ndarray'>
int64


How to find number of dimensions, bytes per element and bytes of memory used?

In [17]:
a=np.array([[1,2,3],[4,5,6]])
print("number of dimensions is :" , a.ndim)
print("number of bytes per element is :" , a.itemsize)
print("number of bytes of memory used is :",a.nbytes)

number of dimensions is : 2
number of bytes per element is : 8
number of bytes of memory used is : 48


Create a null vector of size 10 but the fifth value which is 1

In [19]:
a=np.zeros(10)
print("null vector of size is :",a)
print("making the fifth value as 1")
a[5]=1
print(a)

null vector of size is : [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
making the fifth value as 1
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


Create a vector with values ranging from 10 to 49

In [20]:
a=np.arange(10,49)
print("vector values ranging from 10 to 49 is :",a)

vector values ranging from 10 to 49 is : [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


Reverse a vector (first element becomes last)

In [24]:
a=np.arange(10,20)
print("before reeversing :",a)
a=a[::-1]
print("after reversing :",a)

before reeversing : [10 11 12 13 14 15 16 17 18 19]
after reversing : [19 18 17 16 15 14 13 12 11 10]


Create a 3x3 matrix with values ranging from 0 to 8

In [28]:
a=np.arange(0,9)
a.shape
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Find indices of non-zero elements from [1,2,0,0,4,0]

In [52]:
a=np.array([1,2,0,0,4,0])
Res=np.where(a!=0)[0]
print(Res)
print("indices of non-zero elements are :",np.nonzero(a))

[0 1 4]
indices of non-zero elements are : (array([0, 1, 4]),)


Create a 3x3 identity matrix

In [61]:
a=np.zeros((3,3))

a[0,0]=1
a[1,1]=1
a[2,2]=1
print(a)

print("")
print("")
print("")
print("")
print("")
print("")

#OR
a1=np.eye(3)
print(a1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]






[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create a 3x3x3 array with random values

In [64]:
a=np.random.random((3,3,3))
print(a)

[[[0.14690291 0.59168361 0.42614458]
  [0.23616197 0.41967175 0.45518481]
  [0.72313094 0.2577119  0.87279692]]

 [[0.82072531 0.90674173 0.00268548]
  [0.87494831 0.87378806 0.40150325]
  [0.78795417 0.66504075 0.72018379]]

 [[0.38215981 0.62542862 0.57241669]
  [0.85407371 0.17145951 0.89923053]
  [0.42106893 0.30856326 0.4976838 ]]]


Create a 10x10 array with random values and find the minimum and maximum values

In [71]:
a=np.random.random((10,10))
print(a)
print("minimum value is :",np.min(a))
print("maximum value is :",np.max(a))

[[0.81242995 0.24216606 0.55789977 0.88553545 0.04383758 0.44620132
  0.21492262 0.06317282 0.09522891 0.63966929]
 [0.64669433 0.55188504 0.90043544 0.94055033 0.00142428 0.21400455
  0.34142882 0.57431818 0.02450782 0.53165676]
 [0.51316048 0.49732863 0.40267578 0.38811987 0.80664939 0.91577562
  0.33678596 0.25369298 0.85272002 0.29784787]
 [0.65225611 0.06389445 0.71441333 0.02964057 0.82094192 0.76774745
  0.03899721 0.30183222 0.92815939 0.11235206]
 [0.88055261 0.01486533 0.64476423 0.77636366 0.5315657  0.5409997
  0.37908612 0.02304592 0.4089387  0.05101427]
 [0.55739525 0.82491189 0.73707134 0.0029742  0.56720711 0.06663062
  0.68997774 0.6929888  0.49158613 0.04271923]
 [0.15729794 0.71268733 0.73665009 0.12713718 0.18643527 0.20488879
  0.0831451  0.87163545 0.75861617 0.30008273]
 [0.13229541 0.61564867 0.42836982 0.33893231 0.01640202 0.42520586
  0.94776062 0.44022797 0.87927472 0.49591998]
 [0.41558362 0.56735737 0.46718929 0.65116685 0.51264425 0.04298836
  0.1340699  

Create a random vector of size 30 and find the mean value

In [77]:
a=np.random.random((30))
print(a)
print("mean value of the random vector of size 30 is :",np.mean(a))

[0.13773456 0.53955525 0.43656624 0.01859988 0.14480039 0.45566746
 0.53492766 0.26906817 0.06306037 0.22449641 0.98676073 0.59031876
 0.09029622 0.56754118 0.35176547 0.89373457 0.17820815 0.31572181
 0.46075923 0.57897146 0.24975269 0.47229094 0.24942191 0.49405301
 0.56366368 0.05528546 0.22620019 0.88819894 0.0506867  0.86374457]
mean value of the random vector of size 30 is : 0.3983950686753683


Create a 2d array with 1 on the border and 0 inside

In [88]:
a= np.ones((5,5))
print("Original array:")
print(a)
print("1 on the border and 0 inside in the array")
a[1:-1,1:-1] = 0
print(a)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


How to add a border (filled with 0's) around an existing array? 

In [89]:
a=np.ones((3,3))
print("original array is ")
print(a)
print("0 on the border and 1 insode the array ")
a=np.pad(a,pad_width=1,mode='constant',constant_values=0)
print(a)

original array is 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 insode the array 
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [110]:
a=np.arange(1,15).reshape(2,7)
print(a)
#get 13
print("getting 13")
print(a[1,5])
#get first row
print("getting first row only")
print(a[0])
#get third column
print("getting the third column")
print(a[:,2])
#get only 2,4,6
print("getting 2,4,6")
print(a[0,1],a[0,3],a[0,5])
#replace 13 by 20
print("replacing 13 by 20")
a[1,5]=20
print(a)



[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
getting 13
13
getting first row only
[1 2 3 4 5 6 7]
getting the third column
[ 3 10]
getting 2,4,6
2 4 6
replacing 13 by 20
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


How to Convert a 1D array to a 2D array with 2 rows

In [119]:
a=np.array([1,2,3,4,5,6,7,8])
print(a)
print(np.ndim(a))
a=a.reshape(2,4)
print(a)
print(np.ndim(a))


[1 2 3 4 5 6 7 8]
1
[[1 2 3 4]
 [5 6 7 8]]
2


Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])`
Desired Output:

#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


In [124]:
a=np.array([1,2,3])
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Write a program to show how Numpy taking less memory compared to Python List?



In [133]:
import sys
import numpy as np

l=range(100)
print("size of each element in bytes :",sys.getsizeof(l))
print("size of whole list in bytes :",sys.getsizeof(l)*len(l))

a=np.arange(100)
print("size of each element in numpy array :",a.itemsize)
print("size of whole numpy array in bytes :",a.itemsize*a.size)

size of each element in bytes : 48
size of whole list in bytes : 4800
size of each element in numpy array : 8
size of whole numpy array in bytes : 800


Write a program to show how Numpy taking less time compared to Python List?

In [135]:
import time 
import sys 
size=1000000
l1=range(size)
l2=range(size)
n1=np.arange(size)
n2=np.arange(size)

#list item wise sum
start=time.time()
result=[(x+y) for x,y in zip(l1,l2)]
print("time taken to print python list")
print((time.time()-start)*1000)

#numpy array itemwise sum
start=time.time()
result=n1+n2
print("time taken to print numpy array")
print((time.time()-start)*1000)

time taken to print python list
109.58337783813477
time taken to print numpy array
18.0513858795166
